In [75]:
import numpy as np
import pandas as pd

# Load data
data=pd.read_csv('HR_comma_sep.csv')

data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Departments  \
0                   3              0     1                      0       sales   
1                   6              0     1                      0       sales   
2                   4              0     1                      0       sales   
3                   5              0     1                      0       sales   
4                   3              0     1                      0       sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   Departments            14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [79]:
#displays the count of each class in the column
data['Departments'].value_counts()


Departments
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [81]:
#finds the unique classes in the column
data['Departments'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [83]:
data['salary'].unique()

array(['low', 'medium', 'high'], dtype=object)

In [85]:
# Import LabelEncoder
#label encoding is done to convert categorical data to numerical form
#neural network operate on numerical data

from sklearn import preprocessing

# Creating labelEncoder
le = preprocessing.LabelEncoder()
print(le)
# Converting string labels into numbers.
data['salary']=le.fit_transform(data['salary'])
data['Departments']=le.fit_transform(data['Departments'])

LabelEncoder()


In [87]:
data['salary'].unique()

array([1, 2, 0])

In [89]:
# Spliting data into Feature and
X=data[['satisfaction_level', 'last_evaluation', 'number_project', 'average_montly_hours', 'time_spend_company',
        'Work_accident', 'promotion_last_5years','Departments','salary']]

y=data['left']

#random_state=42 ensures that the split will always produce the same training and testing sets each time the code runs.
# Import train_test_split function
from sklearn.model_selection import train_test_split
#Synthetic Minority Over-sampling Technique
from imblearn.over_sampling import SMOTE
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  # 70% training and 30% test



# Apply SMOTE to oversample the minority class
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)


In [121]:
X_train_resampled.shape

(16000, 9)

In [123]:
y_train_resampled.shape

(16000,)

In [157]:
# Import MLPClassifer
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
# Create model object
clf = MLPClassifier(
                    hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01,
                   
                   )

# Initialize the scaler
scaler = StandardScaler()

# Fit the scaler on the training data
X_train_scaled = scaler.fit_transform(X_train_resampled)

# Fit data onto the model
clf.fit(X_train_scaled,y_train_resampled)

Iteration 1, loss = 0.47583869
Iteration 2, loss = 0.22780590
Iteration 3, loss = 0.18942125
Iteration 4, loss = 0.17987283
Iteration 5, loss = 0.17398768
Iteration 6, loss = 0.17078447
Iteration 7, loss = 0.17139053
Iteration 8, loss = 0.16899319
Iteration 9, loss = 0.16810211
Iteration 10, loss = 0.16773351
Iteration 11, loss = 0.16638722
Iteration 12, loss = 0.16598564
Iteration 13, loss = 0.16518329
Iteration 14, loss = 0.16393783
Iteration 15, loss = 0.16359025
Iteration 16, loss = 0.16238285
Iteration 17, loss = 0.15812315
Iteration 18, loss = 0.15879791
Iteration 19, loss = 0.15631711
Iteration 20, loss = 0.15851523
Iteration 21, loss = 0.15517011
Iteration 22, loss = 0.15628004
Iteration 23, loss = 0.15527573
Iteration 24, loss = 0.15298591
Iteration 25, loss = 0.15261649
Iteration 26, loss = 0.15327504
Iteration 27, loss = 0.15206572
Iteration 28, loss = 0.15099607
Iteration 29, loss = 0.15058354
Iteration 30, loss = 0.14987960
Iteration 31, loss = 0.14839265
Iteration 32, los

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [165]:
# Make prediction on test dataset
X_test_scaled=scaler.transform(X_test)
ypred=clf.predict(X_test_scaled)

# Import accuracy score
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,ypred)

0.9544444444444444

In [167]:
X_test_scaled.shape

(4500, 9)

In [169]:
from sklearn.metrics import classification_report
print(classification_report(y_test, ypred))


              precision    recall  f1-score   support

           0       0.97      0.97      0.97      3428
           1       0.91      0.90      0.90      1072

    accuracy                           0.95      4500
   macro avg       0.94      0.93      0.94      4500
weighted avg       0.95      0.95      0.95      4500



In [195]:
n=[[0.78,0.53,2,157,3,0,0,1,1]]
scaled=scaler.transform(n)
scaled

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.8480654 , -1.05606914, -1.26445365, -0.86854526, -0.47055023,
        -0.33472049, -0.12340351, -1.72392745, -0.53642109]])

In [197]:

new_data=clf.predict(scaled)
print(new_data)


[0]


In [183]:
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(X_test_scaled)
print(confusion_matrix(y_test, y_pred))


[[3333   95]
 [ 110  962]]


In [185]:
print(y_train.value_counts())
print(y_test.value_counts())


left
0    8000
1    2499
Name: count, dtype: int64
left
0    3428
1    1072
Name: count, dtype: int64
