In [2]:
import numpy as np
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
type(array1)

numpy.ndarray

In [6]:
#2-D Array
arr2=np.array([[1,2,3.3],
              [4,5,6.5]])
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
arrex=np.array([
                [
                    [1,2],
                    [3,4]
                ],
                [
                    [5,6],
                    [7,8]
                ]
])
arrex

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
arr4=np.array([[[1,2,3],
               [4,5,6],
               [6,7,8]],
               [[10,11,12],
               [14,15,16],
               [17,18,19]]])
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [14, 15, 16],
        [17, 18, 19]]])

In [14]:
#passing elements as tuple
arr5=np.array((12,13,14))
arr5

array([12, 13, 14])

In [17]:
#No of dimensions
print(arr4.ndim)

3


In [24]:
#ndimin defines the no of dimesnsions you want 
arr10=np.array([1,2,3,9,12],ndmin=6)
arr10
print(arr10.ndim)

6


In [26]:
arr10.shape

(1, 1, 1, 1, 1, 5)

In [31]:
#Indexing in array
print(arr2)
print(arr2[1][1])

[[1.  2.  3.3]
 [4.  5.  6.5]]
5.0


In [33]:
for x in range(0,2):
    for y in range(0,3):
        print(arr2[x][y])

1.0
2.0
3.3
4.0
5.0
6.5


In [35]:
array1.shape

(3,)

In [37]:
arr2.shape

(2, 3)

In [41]:
arr4.dtype,arr5.dtype

(dtype('int32'), dtype('int32'))

In [43]:
array2conv=arr2.astype('i')
array2conv

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [46]:
arr11=np.array([1,2,3,4,5],dtype='S')
arr11

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [48]:
arr2float=arr2.astype('f')
arr2float

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]], dtype=float32)

In [52]:
numone=np.zeros((2,2),dtype=int)
numone

array([[0, 0],
       [0, 0]])

In [55]:
num2=np.ones((3,2),dtype=int)
num2

array([[1, 1],
       [1, 1],
       [1, 1]])

In [61]:
num4=np.eye(3,dtype=int)
num4

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [66]:
range_array=np.arange(6,10,3)
range_array

array([6, 9])

In [75]:
a=np.random.randint(low=4,size=(4))
a

array([3, 0, 1, 3])

In [77]:
flatarr=arr4.flatten()
flatarr

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8, 10, 11, 12, 14, 15, 16, 17, 18,
       19])